# Файл docker-compose должен начинаться с тега версии
version: "3"
# Docker-composes работает с сервисами. 1 сервис = 1 контейнер. Сервисом может быть клиент, сервер, сервер баз данных...
# Раздел, в котором будут описаны сервисы, начинается с 'services'.
services:
  application:
    #build задает путь к dockerfile  
    build: ./
    #перенаправление порта на порт сервера
    ports:
      - 1234:1234
    # Ключевое слово 'depends_on' позволяет указывать, должен ли сервис,
    # прежде чем запуститься, ждать, когда будут готовы к работе другие сервисы.
    # Нам нужно, чтобы сервис 'app' дождался бы готовности к работе сервиса 'db'.
    depends_on:
      - db
